export const FALLBACK_USERS = ['JAKUB', 'ZOSIA'];
export const HOUSEHOLD_VIEW = 'RAZEM';
export const DEFAULT_HOUSEHOLD_GOAL = 500000;
export const SUBCATEGORIES_BY_TYPE = {
  OBLIGACJE: ['TRZYLETNIE', 'DZIESIECIOLETNIE', 'DWUNASTOLETNIE'],
  GIELDA: ['ZLOTO', 'RYNKI_ROZWINIETE', 'RYNKI_ROZWIJAJACE_SIE'],
  IKE: ['ZLOTO', 'RYNKI_ROZWINIETE', 'RYNKI_ROZWIJAJACE_SIE'],
  IKZE: ['ZLOTO', 'RYNKI_ROZWINIETE', 'RYNKI_ROZWIJAJACE_SIE']
};
export const DEFAULT_STOCK_TARGET_ALLOCATIONS = { ZLOTO: 40, RYNKI_ROZWINIETE: 30, RYNKI_ROZWIJAJACE_SIE: 30 };
export const STOCK_SUBCATEGORIES = Object.keys(DEFAULT_STOCK_TARGET_ALLOCATIONS);
export const GLOBAL_ASSET_CLASSES = ['BONDS', 'STOCKS', 'GOLD'];
export const DEFAULT_GLOBAL_TARGET_ALLOCATIONS = { BONDS: 50, STOCKS: 30, GOLD: 20 };
export const CASH_TYPES = ['KONTO_OSZCZEDNOSCIOWE', 'KONTO_BANKOWE', 'PPO', 'PPK'];

export function subcategoriesFor(type) {
  return SUBCATEGORIES_BY_TYPE[type] || [];
}
